using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Calculation.Enums;
using Calculation.Interfaces;

namespace Storage.Database
{
    public partial class DbSolution1D : ISolution1D
    {
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Name of the solution.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Current time index.
        /// </summary>
        public int Nt { get; internal set; }

        [NotMapped]
        public object Key
        {
            get { return Id; }
        }

        /// <summary>
        /// Datetime, when solution has been started.
        /// </summary>
        public DateTime Started { get; set; }

        /// <summary>
        /// Solution state.
        /// </summary>
        public SolutionState State { get; internal set; }

        /// <summary>
        /// Serialized.
        /// </summary>
        public string PhysicalData { get; set; }

        /// <summary>
        /// Type.
        /// </summary>
        public string Solver { get; set; }

        /// <summary>
        /// Is solution generated by analytic formula.
        /// </summary>
        public bool IsExact { get; set; }

        /// <summary>
        /// Is solution dependent on time.
        /// </summary>
        public bool IsTimeDependent { get; set; }

        /// <summary>
        /// Delta time.
        /// </summary>
        public double dt { get; set; }

        public int DbGridId { get; set; }

        public virtual DbGrid1D DbGrid { get; set; }
        public virtual ICollection<DbLayer1D> DbLayers { get; set; }
    }
}