//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculation {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class CalculationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CalculationSettings defaultInstance = ((CalculationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CalculationSettings())));
        
        public static CalculationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BundleMaxBufferSize {
            get {
                return ((int)(this["BundleMaxBufferSize"]));
            }
            set {
                this["BundleMaxBufferSize"] = value;
            }
        }
    }
}
